# 夕雾缀理 - 幸せのリボン
[[redirects]]
from = "/ribbon"
status = 302
to = "https://www.bilibili.com/video/av114618534004449/"

[[redirects]]
from = "/askme"
status = 302
to = "https://github.com/outloudvi/askme"

[[redirects]]
from = "/*"
status = 200
to = "/index.html"

[[headers]]
for = "/*"
[headers.values]
Permissions-Policy = "geolocation=(), camera=(), microphone=(), interest-cohort=()"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
