# 夕雾缀理 - 幸せのリボン
[[redirects]]
from = "/ribbon"
status = 302
to = "https://www.bilibili.com/video/av114618534004449/"
[redirects.headers]
X-Robots-Tag = "none"

# somunia / nyankobrq & yaca - twinkle night
[[redirects]]
from = "/tw"
status = 302
to = "https://www.bilibili.com/video/av61810777/"
conditions = { Language = ["zh"] }
[redirects.headers]
X-Robots-Tag = "none"

[[redirects]]
from = "/tw"
status = 302
to = "https://www.youtube.com/watch?v=uUvthLpSHrQ"
[redirects.headers]
X-Robots-Tag = "none"

[[redirects]]
from = "/askme"
status = 302
to = "https://github.com/outloudvi/askme"

[[redirects]]
from = "/askme/pubkey.gpg"
status = 302
to = "https://github.com/outloudvi/askme/raw/refs/heads/master/pubkey.gpg"

[[headers]]
for = "/*"
[headers.values]
Permissions-Policy = "geolocation=(), camera=(), microphone=(), interest-cohort=()"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"

[[headers]]
for = "/.well-known/nostr.json"
[headers.values]
Access-Control-Allow-Origin = "*"
